services:
  - type: web
    name: nexus-ecommerce
    env: node
    buildCommand: npm install && npm run build-client
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://nexus-ecommerce-chi.vercel.app