services:
  # Backend API service
  - type: web
    name: nexus-ecommerce-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    nodeVersion: 22.16.0
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        value: mongodb+srv://soumyamajumder201817_db_user:nspL11g0bWzlWZHa@nexusecommerceapi.vp5ywmd.mongodb.net/nexus-ecommerce?appName=nexusEcommerceApi
      - key: JWT_SECRET
        value: b6f31e28071363376dc3c5b4256b4c505feff8bf324184ddda2b3c431ceed57b
      - key: CLOUDINARY_CLOUD_NAME
        value: dm4hy8ivc
      - key: CLOUDINARY_API_KEY
        value: 577196911234224
      - key: CLOUDINARY_API_SECRET
        value: D5jkTEHU-Y8JNjk8gSUBhsX0GJI
      - key: RAZORPAY_KEY_ID
        value: your_razorpay_key_id
      - key: RAZORPAY_KEY_SECRET
        value: your_razorpay_key_secret
      - key: GEMINI_API_KEY
        value: AIzaSyCL1kv6TyxxWSKiNEOqmx-krtqsWOhbMLk
    domains:
      - nexus-ecommerce-api.onrender.com

  # Frontend web service
  - type: web
    name: nexus-ecommerce-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: ./build
    nodeVersion: 22.16.0
    domains:
      - nexus-ecommerce-chi.vercel.app